chinchillacollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    path('chinchillas/', views.ChinchillaList.as_view(), name='index'),
    path('chinchillas/<int:chinchilla_id>/', views.chinchillas_detail, name='detail'),
    path('chinchillas/create/', views.ChinchillaCreate.as_view(), name='chinchillas_create'),
    path('chinchillas/<int:pk>/update/', views.ChinchillaUpdate.as_view(), name='chinchillas_update'),
    path('chinchillas/<int:pk>/delete/', views.ChinchillaDelete.as_view(), name='chinchillas_delete'),
    path('chinchillas/<int:chinchilla_id>/add_bath/', views.add_bath, name='add_bath'),
    path('chinchillas/<int:chinchilla_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('chinchillas/<int:chinchilla_id>/add_photo/', views.add_photo, name='add_photo'),
    path('chinchillas/<int:chinchilla_id>/add_toy/<int:toy_id>/', views.add_toy, name='add_toy'),
    path('chinchillas/<int:chinchilla_id>/remove_toy/<int:toy_id>/', views.remove_toy, name='remove_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})

class Chinchilla(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'chinchilla_id': self.id})
    
class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    chinchilla = models.ForeignKey(Chinchilla, on_delete=models.CASCADE)
    
    def __str__(self):
        return  f'{self.get_meal_display()} on {self.date}'
    
    class Meta:
        ordering = ['-date']
          
class Bath(models.Model):
    date = models.DateField('Bath Date')
    chinchilla = models.ForeignKey(Chinchilla, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.get_bath_display()} on {self.date}'
    
    class Meta:
        ordering = ['-date']
        
class Photo(models.Model):
    url = models.CharField(max_length=300)
    chinchilla = models.ForeignKey(Chinchilla, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Photo for chinchilla_id: {self.chinchilla_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding, Bath

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
  
class BathForm(ModelForm):
    class Meta:
        model = Bath
        fields = ['date']      

main_app/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Chinchilla, Toy, Photo
from .forms import BathForm, FeedingForm
import uuid
import boto3

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'catcollector-sei-cc-8'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def chinchillas_detail(request, chinchilla_id):
    chinchilla = Chinchilla.objects.get(id=chinchilla_id)
    toys_available = Toy.objects.exclude(id__in = chinchilla.toys.all().values_list('id'))
    feeding_form = FeedingForm()
    bath_form = BathForm()
    return render(request, 'chinchillas/detail.html', {
        'chinchilla': chinchilla,
        'feeding_form': feeding_form,
        'bath_form': bath_form,
        'toys': toys_available,
    })

class ChinchillaList(LoginRequiredMixin, ListView):
    model = Chinchilla
    # queryset = Chinchilla.objects.filter(chinchilla.user=)
    
class ChinchillaCreate(LoginRequiredMixin, CreateView):
    model = Chinchilla
    fields = ['name', 'color', 'description', 'age']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class ChinchillaUpdate(LoginRequiredMixin, UpdateView):
    model = Chinchilla
    fields = ['color', 'description', 'age']
    
class ChinchillaDelete(LoginRequiredMixin, DeleteView):
    model = Chinchilla
    success_url = '/chinchillas/'

@login_required 
def add_bath(request, chinchilla_id):
    form = BathForm(request.POST)
    if form.is_valid():
        new_bath = form.save(commit=False)
        new_bath.chinchilla_id = chinchilla_id
        new_bath.save()
    return redirect('detail', chinchilla_id=chinchilla_id)

@login_required
def add_feeding(request, chinchilla_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.chinchilla_id = chinchilla_id
        new_feeding.save()
    return redirect('detail', chinchilla_id=chinchilla_id)

@login_required
def add_photo(request, chinchilla_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, chinchilla_id=chinchilla_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', chinchilla_id=chinchilla_id)

class ToyList(LoginRequiredMixin, ListView):
    model = Toy

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = '__all__'

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = ['name', 'color']

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys/'

@login_required
def add_toy(request, chinchilla_id, toy_id):
    Chinchilla.objects.get(id=chinchilla_id).toys.add(toy_id)
    return redirect('detail', chinchilla_id=chinchilla_id)

@login_required
def remove_toy(request, chinchilla_id, toy_id):
    Chinchilla.objects.get(id=chinchilla_id).toys.remove(toy_id)
    return redirect('detail', chinchilla_id=chinchilla_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again!'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Chinchilla Collector</h1>
<hr />
<p>Add chinchillas and give them toys! Oh, and don't forget to feed them!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Chinchilla Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav class="green">
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Chinchilla Collector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'chinchillas_create' %}">Add a Chinchilla</a></li>
                    <li><a href="{% url 'index' %}">View All Chinchillas</a></li>
                    <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
                    <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer green">
        <div class="right">All Rights Reserved, &copy; 2020 Chinchilla Collector &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/chinchillas/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Chinchilla Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ chinchilla.name }}</span>
                <p>Color: {{ chinchilla.color }}</p>
                <p>Description: {{ chinchilla.description }}</p>
                <p>Age: {{ chinchilla.age }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'chinchillas_update' chinchilla.id %}">Edit</a>
                <a href="{% url 'chinchillas_delete' chinchilla.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                {% for photo in chinchilla.photo_set.all %}
                <img class="responsive-img card-panel" src="{{photo.url}}">
                {% empty %}
                <div class="card-panel teal-text center-align">No Photos Uploaded</div>
                {% endfor %}
                <form action="{% url 'add_photo' chinchilla.id %}" enctype="multipart/form-data" method="POST"
                    class="card-panel">
                    {% csrf_token %}
                    <input type="file" name="photo-file">
                    <br><br>
                    <input type="submit" class="btn" value="Upload Photo">
                </form>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_bath' chinchilla.id %}" method="post">
            {% csrf_token %}
            {{ bath_form.as_p }}
            <input type="submit" class="btn" value="Give {{chinchilla.name}} a Bath">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                {% for bath in chinchilla.bath_set.all %}
                <tr>
                    <td>{{bath.date}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col s6">
        <form action="{% url 'add_feeding' chinchilla.id %}" method="post">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <input type="submit" class="btn" value="Add Feeding">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in chinchilla.feeding_set.all %}
                <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ chinchilla.name }}'s Toys</h3>
        {% if chinchilla.toys.count %}
        {% for toy in chinchilla.toys.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'remove_toy' chinchilla.id toy.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Remove</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>This Chinchilla Has No Toys!</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Toys</h3>
        {% if toys.count %}
        {% for toy in toys.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'add_toy' chinchilla.id toy.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{chinchilla.name}} Already Has All Toys Available</h5>
        {% endif %}
    </div>
</div>
<script>
    const dateEl = document.querySelectorAll('[id=id_date]');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home Page</h1>

{% endblock %}

main_app/templates/main_app/chinchilla_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Chinchilla</h1>

<h4>Are you sure you want to delete {{ object.name }}?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete" class="btn">
    <a href="{% url 'detail' chinchilla.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/chinchilla_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit {{object.name}}</h1>
{% else %}
    <h1>Add Chinchilla</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="{% if object %}Update{% else %}Create{% endif %} Chinchilla" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/chinchilla_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Chinchilla List</h1>

{% for chinchilla in object_list %}
<a href="{% url 'detail' chinchilla.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ chinchilla.name }}</span>
            <p>Color: {{ chinchilla.color }}</p>
            <p>Description: {{ chinchilla.description }}</p>
            <p>Age: {{ chinchilla.age }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Toy</h1>
<h4>Are you sure you want to delete {{ object.name }}?</h4>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>
<div class="row">
    <div class="col s6 col-offset-3">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ toy.name }}</span>
                <p>Color: {{ toy.color }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'toys_update' toy.id %}">Edit</a>
                <a href="{% url 'toys_delete' toy.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit {{object.name}}</h1>
{% else %}
    <h1>Add Toy</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>
{% for toy in toy_list %}
<a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}